const resList = [
    {
        info: {
            id: '445762',
            name: 'Burger King',
            cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
            locality: 'Kote MR Plaza',
            areaName: 'Sanjay Nagar',
            costForTwo: '₹350 for two',
            cuisines: ['Burgers', 'American'],
            avgRating: 4.3,
            parentId: '166',
            avgRatingString: '4.3',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 19,
                lastMileTravel: 1.5,
                serviceability: 'SERVICEABLE',
                slaString: '19 mins',
                lastMileTravelString: '1.5 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: '',
                                    fontColor: '#7E808C',
                                    iconId:
                                        'v1702882113/Ratnesh_Badges/20x20_px_kids__20px.png',
                                    shortDescription: 'Kids Favourite options',
                                },
                            },
                        ],
                    },
                },
            },
            aggregatedDiscountInfoV3: {
                header: '60% OFF',
                subHeader: 'UPTO ₹120',
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/burger-king-kote-mr-plaza-sanjay-nagar-bangalore-445762',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '618083',
            name: "La Pino'z Pizza",
            cloudinaryImageId: 'd3pgrav1whn3gzcvy5qk',
            locality: 'Outer Ring Road',
            areaName: 'Kadubeesanahalli',
            costForTwo: '₹400 for two',
            cuisines: ['Pizzas', 'Pastas', 'Italian', 'Desserts', 'Beverages'],
            avgRating: 4,
            parentId: '4961',
            avgRatingString: '4.0',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 23,
                lastMileTravel: 4.7,
                serviceability: 'SERVICEABLE',
                slaString: '23 mins',
                lastMileTravelString: '4.7 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-24 03:00:00',
                opened: true,
            },
            badges: {
                textExtendedBadges: [
                    {
                        iconId: 'v1702882113/Ratnesh_Badges/20x20_px_kids__20px.png',
                        shortDescription: 'Kids Favourite options',
                        fontColor: '#7E808C',
                    },
                ],
            },
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {
                        badgeObject: [
                            {
                                attributes: {
                                    description: '',
                                    fontColor: '#7E808C',
                                    iconId:
                                        'v1702882113/Ratnesh_Badges/20x20_px_kids__20px.png',
                                    shortDescription: 'Kids Favourite options',
                                },
                            },
                        ],
                    },
                },
            },
            aggregatedDiscountInfoV3: {
                header: '₹125 OFF',
                subHeader: 'ABOVE ₹699',
                discountTag: 'FLAT DEAL',
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/la-pinoz-pizza-outer-ring-road-kadubeesanahalli-bangalore-618083',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '661411',
            name: 'AL-Arabic Shawarma',
            cloudinaryImageId: 'b628e1f3e285b7f6d0a47df825d1babf',
            locality: "G M Reddy's Royale Apartments",
            areaName: 'Bellandur Sarjapur',
            costForTwo: '₹300 for two',
            cuisines: ['Arabian', 'Snacks', 'Beverages'],
            avgRating: 4.3,
            parentId: '396951',
            avgRatingString: '4.3',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 26,
                lastMileTravel: 7.1,
                serviceability: 'SERVICEABLE',
                slaString: '26 mins',
                lastMileTravelString: '7.1 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-24 07:00:00',
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '₹50 OFF',
                subHeader: 'ABOVE ₹999',
                discountTag: 'FLAT DEAL',
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/al-arabic-shawarma-g-m-reddys-royale-apartments-bellandur-sarjapur-bangalore-661411',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '699329',
            name: 'The fritter company',
            cloudinaryImageId: '81a4a575e0298eece46ed46cfe4f21cf',
            locality: 'Near shell petrol pump',
            areaName: 'Bellandur Sarjapur',
            costForTwo: '₹350 for two',
            cuisines: ['American', 'Burgers', 'Beverages'],
            avgRating: 4.2,
            parentId: '21135',
            avgRatingString: '4.2',
            totalRatingsString: '100+',
            sla: {
                deliveryTime: 36,
                lastMileTravel: 8.9,
                serviceability: 'SERVICEABLE',
                slaString: '36 mins',
                lastMileTravelString: '8.9 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-24 06:00:00',
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '20% OFF',
                subHeader: 'ABOVE ₹700',
                discountTag: 'FLAT DEAL',
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/the-fritter-company-near-shell-petrol-pump-bellandur-sarjapur-bangalore-699329',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '88340',
            name: 'Kolkata restaurant',
            cloudinaryImageId: 'df6mmava4ld3wtyhfb26',
            locality: 'Munnekollal',
            areaName: 'Marathahalli',
            costForTwo: '₹199 for two',
            cuisines: ['North Indian', 'Chinese', 'Biryani', 'Seafood'],
            avgRating: 3.7,
            parentId: '22125',
            avgRatingString: '3.7',
            totalRatingsString: '1K+',
            sla: {
                deliveryTime: 26,
                lastMileTravel: 4,
                serviceability: 'SERVICEABLE',
                slaString: '26 mins',
                lastMileTravelString: '4.0 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-24 05:00:00',
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '₹125 OFF',
                subHeader: 'ABOVE ₹499',
                discountTag: 'FLAT DEAL',
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/kolkata-restaurant-munnekollal-marathahalli-bangalore-88340',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '113861',
            name: 'HOMMS',
            cloudinaryImageId: 'vimuysflcfsaho5ip6ow',
            locality: 'Vyjayanthi Mala complex',
            areaName: 'Mahadevpura',
            costForTwo: '₹300 for two',
            cuisines: ['Chinese', 'Asian'],
            avgRating: 4.2,
            parentId: '14566',
            avgRatingString: '4.2',
            totalRatingsString: '10K+',
            sla: {
                deliveryTime: 20,
                lastMileTravel: 4.4,
                serviceability: 'SERVICEABLE',
                slaString: '20 mins',
                lastMileTravelString: '4.4 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-24 02:45:00',
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/homms-vyjayanthi-mala-complex-mahadevpura-bangalore-113861',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '692371',
            name: 'Donne Biryani @99',
            cloudinaryImageId: '1e88d6b0986ca2bbbc89841219da8932',
            locality: 'Chinnapanahalli',
            areaName: 'Near Shuchodaya Apartment',
            costForTwo: '₹200 for two',
            cuisines: ['Biryani', 'Chinese', 'Snacks'],
            avgRating: 3.2,
            parentId: '262680',
            avgRatingString: '3.2',
            totalRatingsString: '100+',
            sla: {
                deliveryTime: 26,
                lastMileTravel: 5,
                serviceability: 'SERVICEABLE',
                slaString: '26 mins',
                lastMileTravelString: '5.0 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-24 10:30:00',
                opened: true,
            },
            badges: {},
            isOpen: true,
            aggregatedDiscountInfoV2: {},
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/donne-biryani-99-chinnapanahalli-near-shuchodaya-apartment-bangalore-692371',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '686288',
            name: 'The Maggi Company',
            cloudinaryImageId: 'af21fd92392ebd6271c6a1c2c2380119',
            locality: 'Sunrise Villas',
            areaName: 'Bellandur Sarjapur',
            costForTwo: '₹300 for two',
            cuisines: ['Snacks'],
            avgRating: 4.3,
            parentId: '317741',
            avgRatingString: '4.3',
            totalRatingsString: '100+',
            sla: {
                deliveryTime: 30,
                lastMileTravel: 7.3,
                serviceability: 'SERVICEABLE',
                slaString: '30 mins',
                lastMileTravelString: '7.3 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-24 16:00:00',
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '₹200 OFF',
                subHeader: 'ABOVE ₹599',
                discountTag: 'FLAT DEAL',
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/the-maggi-company-sunrise-villas-bellandur-sarjapur-bangalore-686288',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
    {
        info: {
            id: '709119',
            name: 'Irani Std. Tea',
            cloudinaryImageId: '1e756ee8d230b65d570f7e8e70f7062c',
            locality: '6th Main Rd',
            areaName: 'Indiranagar',
            costForTwo: '₹200 for two',
            cuisines: ['Beverages', 'Snacks', 'Fast Food'],
            avgRating: 4,
            parentId: '374583',
            avgRatingString: '4.0',
            totalRatingsString: '100+',
            sla: {
                deliveryTime: 26,
                lastMileTravel: 7,
                serviceability: 'SERVICEABLE',
                slaString: '26 mins',
                lastMileTravelString: '7.0 km',
                iconType: 'ICON_TYPE_EMPTY',
            },
            availability: {
                nextCloseTime: '2023-12-30 00:00:00',
                opened: true,
            },
            badges: {},
            isOpen: true,
            type: 'F',
            badgesV2: {
                entityBadges: {
                    imageBased: {},
                    textBased: {},
                    textExtendedBadges: {},
                },
            },
            aggregatedDiscountInfoV3: {
                header: '20% OFF',
                subHeader: 'UPTO ₹120',
            },
            orderabilityCommunication: {
                title: {},
                subTitle: {},
                message: {},
                customIcon: {},
            },
            differentiatedUi: {
                displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
                differentiatedUiMediaDetails: {
                    mediaType: 'ADS_MEDIA_ENUM_IMAGE',
                    lottie: {},
                    video: {},
                },
            },
            reviewsSummary: {},
            displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
            restaurantOfferPresentationInfo: {},
        },
        analytics: {
            context: 'seo-data-baf505c9-97c5-4411-a576-861ec0db45ff',
        },
        cta: {
            link: 'https://www.swiggy.com/restaurants/irani-std-tea-6th-main-rd-indiranagar-bangalore-709119',
            text: 'RESTAURANT_MENU',
            type: 'WEBLINK',
        },
        widgetId: 'collectionV5RestaurantListWidget_SimRestoRelevance_food_seo',
    },
];
export default resList;
